---
title: 'RQ2: Does the interest differ based on the type of TD?'
author: "Yasutaka Kamei"
date: "Feb 11th, 2016"
output: pdf_document

---
# Read Data
```{r}
setwd("/Users/kamei/Research/techdebt/msr16_td_interest/")
source("./r_scripts/data_read.r")
```

# The number of technical debt in each type
```{r}
b <- data.CountLine.all

tmp <- b[b[,"Project"] == "apache-ant", ]
fc <- factor(tmp$Type)
tapply(tmp$interest, fc, length)
tapply(tmp$interest, fc, function(x){length(x)/length(tmp$interest) * 100})

tmp <- b[b[,"Project"] == "apache-jmeter", ]
fc <- factor(tmp$Type)
tapply(tmp$interest, fc, length)
tapply(tmp$interest, fc, function(x){length(x)/length(tmp$interest) * 100})

tmp <- b[b[,"Project"] == "jruby", ]
fc <- factor(tmp$Type)
tapply(tmp$interest, fc, length)
tapply(tmp$interest, fc, function(x){length(x)/length(tmp$interest) * 100})
```

### Observation
- In jruby, three types of technical dept are included than 10%.
- We use DEFECT, DESIGN and REQ in jruby.

# Does the interest differ based on the type of TD?


```{r}
tmp <- b[b[,"Project"] == "jruby", ]
tmp <- tmp[(tmp[,"Type"] == "DEFECT" |  tmp[,"Type"] == "DESIGN" |  tmp[,"Type"] == "REQUIREMENT"),]
fc <- factor(tmp$Type)

tapply(tmp$interest, fc, function(x){c(sum(x==0)/length(x)*100)})

tapply(tmp$interest, fc, summary)

defect <- subset(tmp$interest, tmp[,"Type"] == "DEFECT")
design <- subset(tmp$interest, tmp[,"Type"] == "DESIGN")
req <- subset(tmp$interest, tmp[,"Type"] == "REQUIREMENT")

library(vioplot)

plot(0, 0, type = "n", xlab = "", ylab = "", axes = FALSE,
     xlim = c(0.5, 3.5), ylim = range(c(defect, design, req)))

axis(side = 1, at = 1:3, labels = c("defect", "design", "req"))
axis(side = 2)                                     

vioplot(defect, at = 1, col = "orange", add = TRUE)
vioplot(design, at = 2, col = "seagreen", add = TRUE)
vioplot(req, at = 3, col = "blue", add = TRUE)
```

### Observation
- There is no difference in each category.

# Stat
```{r}

b <- data.CountLine.all
tmp <- b[b[,"Project"] == "jruby", ]
fc <- factor(tmp$Type)
tapply(tmp$interest, fc, length)

b <- data.CountLine.positive
tmp <- b[b[,"Project"] == "jruby", ]
fc <- factor(tmp$Type)
tapply(tmp$interest, fc, length)

b <- data.CountLine.negative
tmp <- b[b[,"Project"] == "jruby", ]
fc <- factor(tmp$Type)
tapply(tmp$interest, fc, length)

b <- data.CountInput.all
tmp <- b[b[,"Project"] == "jruby", ]
fc <- factor(tmp$Type)
tapply(tmp$interest, fc, length)

b <- data.CountInput.positive
tmp <- b[b[,"Project"] == "jruby", ]
fc <- factor(tmp$Type)
tapply(tmp$interest, fc, length)

b <- data.CountInput.negative
tmp <- b[b[,"Project"] == "jruby", ]
fc <- factor(tmp$Type)
tapply(tmp$interest, fc, length)




b <- data.CountLine.positive
tmp <- b[b[,"Project"] == "jruby", ]
fc <- factor(tmp$Type)
interest <- tmp$interest
tapply(interest, fc, summary)


b <- data.CountInput.positive
tmp <- b[b[,"Project"] == "jruby", ]
fc <- factor(tmp$Type)
interest <- tmp$interest
tapply(interest, fc, summary)
```

# Plot
```{r}
library(reshape2)
library(ggplot2)

if(0){
b <- data.CountLine.positive
  
tmp <- b[b[,"Project"] == "jruby", ]
tmp <- tmp[(tmp[,"Type"] == "DEFECT"),]
a1 <- data.frame(Interest=tmp$interest) 
g = ggplot(a1, aes(x=Interest, y=..density.., fill=T), lims(x = c(0,400)))
g = g + geom_density(alpha = 0.5) + xlim(0, 400) + ylim(0,0.03) + guides(fill=FALSE)
print(g)
ggsave(file = "./tex/figures/rq2-defect.pdf", plot = g, width = 8.09, height = 5)

tmp <- b[b[,"Project"] == "jruby", ]
tmp <- tmp[(tmp[,"Type"] == "DESIGN"),]
a2 <- data.frame(Interest=tmp$interest) 
g = ggplot(a2, aes(x=Interest, y=..density.., fill=T, lims(x = c(0,400))))
g = g + geom_density(alpha = 0.5) + xlim(0, 400) + ylim(0,0.03) + guides(fill=FALSE)
print(g)
ggsave(file = "./tex/figures/rq2-design.pdf", plot = g, width = 8.09, height = 5)

tmp <- b[b[,"Project"] == "jruby", ]
tmp <- tmp[(tmp[,"Type"] == "REQUIREMENT"),]
a3 <- data.frame(Interest=tmp$interest) 
g = ggplot(a3, aes(x=Interest, y=..density.., fill=T), lims(x = c(0,400)))
g = g + geom_density(alpha = 0.5) + xlim(0, 400) + ylim(0,0.03) + guides(fill=FALSE)
print(g)
ggsave(file = "./tex/figures/rq2-requirement.pdf", plot = g, width = 8.09, height = 5)

b <- data.CountInput.positive
  
tmp <- b[b[,"Project"] == "jruby", ]
tmp <- tmp[(tmp[,"Type"] == "DEFECT"),]
a1 <- data.frame(Interest=tmp$interest) 
g = ggplot(a1, aes(x=Interest, y=..density.., fill=T), lims(x = c(0,400)))
g = g + geom_density(alpha = 0.5) + xlim(0, 400) + ylim(0,0.03) + guides(fill=FALSE)
print(g)
ggsave(file = "./tex/figures/rq2-defect-countinput.pdf", plot = g, width = 8.09, height = 5)

tmp <- b[b[,"Project"] == "jruby", ]
tmp <- tmp[(tmp[,"Type"] == "DESIGN"),]
a2 <- data.frame(Interest=tmp$interest) 
g = ggplot(a2, aes(x=Interest, y=..density.., fill=T, lims(x = c(0,400))))
g = g + geom_density(alpha = 0.5) + xlim(0, 400) + ylim(0,0.03) + guides(fill=FALSE)
print(g)
ggsave(file = "./tex/figures/rq2-design-countinput.pdf", plot = g, width = 8.09, height = 5)

tmp <- b[b[,"Project"] == "jruby", ]
tmp <- tmp[(tmp[,"Type"] == "REQUIREMENT"),]
a3 <- data.frame(Interest=tmp$interest) 
g = ggplot(a3, aes(x=Interest, y=..density.., fill=T), lims(x = c(0,400)))
g = g + geom_density(alpha = 0.5) + xlim(0, 400) + ylim(0,0.03) + guides(fill=FALSE)
print(g)
ggsave(file = "./tex/figures/rq2-requirement-countinput.pdf", plot = g, width = 8.09, height = 5)
}
```
